# Generated by Django 4.2.6 on 2023-10-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_auto_20230822_2208"),
        ("bootstrap5_jumbotron", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bootstrap5jumbotron",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
